-- db creation
CREATE TABLE `horaires-salles`.courses (
	course_id            int  NOT NULL  AUTO_INCREMENT,
	name                 varchar(1000)    ,
	CONSTRAINT pk_courses_course_id PRIMARY KEY ( course_id )
 ) engine=InnoDB;

CREATE TABLE `horaires-salles`.rooms (
	room_id              int  NOT NULL  AUTO_INCREMENT,
	name                 varchar(100)    ,
	description          varchar(1000)    ,
	CONSTRAINT pk_rooms_room_id PRIMARY KEY ( room_id )
 ) engine=InnoDB;

CREATE TABLE `horaires-salles`.timeslots (
	timeslot_id          int  NOT NULL  AUTO_INCREMENT,
	start_hour           int    ,
	start_minute         int    ,
	end_hour             int    ,
	end_minute           int    ,
	CONSTRAINT pk_timeslots_timeslot_id PRIMARY KEY ( timeslot_id )
 ) engine=InnoDB;

CREATE TABLE `horaires-salles`.weekdays (
	weekday_id           int  NOT NULL  AUTO_INCREMENT,
	name_fr              varchar(100)    ,
	name_en              varchar(100)    ,
	name_de              varchar(100)    ,
	CONSTRAINT pk_weekdays_weekday_id PRIMARY KEY ( weekday_id )
 ) engine=InnoDB;

CREATE TABLE `horaires-salles`.registrations (
	registration_id      int  NOT NULL  AUTO_INCREMENT,
	weekday_id           int    ,
	course_id            int    ,
	room_id              int    ,
	CONSTRAINT pk_registrations_registration_id PRIMARY KEY ( registration_id )
 ) engine=InnoDB;

CREATE INDEX idx_registrations_weekday_id ON `horaires-salles`.registrations ( weekday_id );

CREATE INDEX idx_registrations_course_id ON `horaires-salles`.registrations ( course_id );

CREATE INDEX idx_registrations_room_id ON `horaires-salles`.registrations ( room_id );

CREATE TABLE `horaires-salles`.timeslots_registrations (
	ts_reg_id            int  NOT NULL  AUTO_INCREMENT,
	timeslot_id          int    ,
	registration_id      int    ,
	CONSTRAINT pk_timeslots_registrations_ts_reg_id PRIMARY KEY ( ts_reg_id )
 ) engine=InnoDB;

CREATE INDEX idx_timeslots_registrations_timeslot_id ON `horaires-salles`.timeslots_registrations ( timeslot_id );
CREATE INDEX idx_timeslots_registrations_registration_id ON `horaires-salles`.timeslots_registrations ( registration_id );

ALTER TABLE `horaires-salles`.registrations ADD CONSTRAINT fk_registrations_weekdays FOREIGN KEY ( weekday_id ) REFERENCES `horaires-salles`.weekdays( weekday_id ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE `horaires-salles`.registrations ADD CONSTRAINT fk_registrations_courses FOREIGN KEY ( course_id ) REFERENCES `horaires-salles`.courses( course_id ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE `horaires-salles`.registrations ADD CONSTRAINT fk_registrations_rooms FOREIGN KEY ( room_id ) REFERENCES `horaires-salles`.rooms( room_id ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE `horaires-salles`.timeslots_registrations ADD CONSTRAINT fk_timeslots_registrations FOREIGN KEY ( timeslot_id ) REFERENCES `horaires-salles`.timeslots( timeslot_id ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE `horaires-salles`.timeslots_registrations ADD CONSTRAINT fk_timeslots_registrations2 FOREIGN KEY ( registration_id ) REFERENCES `horaires-salles`.registrations( registration_id ) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- courses
INSERT INTO `courses`(`name`) VALUES
("Allemand 1"),
("Deutsch Grundkurs 1"),
("Maths. 1/Physique 1/All. 1"),
("All. 1/Dét. constr. B/Phys. 1/Maths. 1"),
("Expr. informatique 3D"),
("Anglais 1"),
("Dévelop. durable 3"),
("Algèbre linéaire 1"),
("Méthodologie"),
("Programmation & TP"),
("Analyse 1"),
("Communication 1"),
("Technique numérique 1"),
("Téléinformatique 1"),
("CVSE 1"),
("Dévelop. durable 1"),
("Lineare Algebra 1"),
("Analysis 1"),
("Kommunikation 1"),
("Techniques de réactions 1"),
("Génie chimique 3"),
("Modélisation et simulation"),
("Génie des procédés 3"),
("Procédés de séparation"),
("Biotechnologie"),
("Chimie physique 3"),
("Chimie organique 5"),
("Construction/Kunstruktionslehre 1"),
("Activités interdisciplinaires 1"),
("Modélisation et calcul info. des structures"),
("Constr. acier 1"),
("Conservation d'ouvrage 1"),
("Constr. béton 3"),
("Hydraulique urbaine"),
("Ouvrages géotechniques"),
("Routes et transports 1"),
("Aménagement du territoire"),
("Constr. bois 1"),
("Projet de semestre 3"),
("Traitement des eaux usées"),
("Administration"),
("Constr. ville"),
("Projet d'architecture 1"),
("Statique 1"),
("Sém. constr./Konstruktionssem. 1"),
("Théorie de l'archi. 1"),
("Gestion et droit 1"),
("Se documenter"),
("Matériaux de l'ingénieur 1"),
("Bilan d'énergie"),
("Histoire de l'archi. 3"),
("Structure  1"),
("Histoire de l'archi. 5"),
("Histoire de l'architecture 1"),
("Génie des procédés 1"),
("Analyse instrumentale"),
("Génie chimique 1"),
("Analyse 3"),
("Chimie physique 1"),
("Régulation 1"),
("Automatisation 1"),
("Analyse spectrale"),
("Chimie organique 3"),
("TP Chi phy1/ Ana instr 2"),
("MLS-S01"),
("MLS-S05"),
("MLS-S04"),
("Coachings"),
("TP Chimie Organique 1"),
("TP Chi Org1/Phy3"),
("TP Chimie gén &ana 1"),
("TP Physique 3"),
("TP 31 Physique 3"),
("Physik 1"),
("Physique 1"),
("Physique 3"),
("Electrotechnique"),
("Physique TIC 1"),
("Construction 3/Konstruktionslehre 3"),
("Physique du bâtiment 1"),
("Métrologie"),
("Gestion et droit 3"),
("Physique du bâtiment 3"),
("Structure 3"),
("Physik 3"),
("ex. renov. énerg./energ. Sanierung"),
("Séminaire S3"),
("Electromécanique"),
("DAO/Dessin"),
("Mathématiques"),
("Communication"),
("Prescriptions de métrage et métrés"),
("Construction de routes"),
("Analyse de prix"),
("Installations et programmes"),
("Statique et RDM"),
("Inventaire de chantier"),
("Topométrie"),
("Conduite des travaux"),
("Technologie des matériaux"),
("Conduite du personnel"),
("Construction du bâtiment"),
("Allemand"),
("Machines de chantier"),
("Informatique"),
("Devis et avant-métrés"),
("Construction en béton"),
("Physique du bâtiment"),
("Fondations, sous-oeuvres"),
("Statique et rés. mat./CVSE"),
("Géotechnique"),
("Comptabilité d'entreprise et économie"),
("Laboratoire des matériaux"),
("Droit"),
("TP Rés. et appl. IT/Syst. d'info"),
("TP 52 Trait. signal/Concep élec/de sys num"),
("Conception électronique"),
("TP Systèmes d'exploitation 1"),
("TP Systèmes embarqués 1"),
("TP 51 Circ. intégrés & Haute fréq/Info tech"),
("TP Sécurité IT 1"),
("Projet TIC"),
("TP Tec. tel./Sys. emb."),
("TP Trait. images/Tec. tel./Sys. emb."),
("TP Embedded Systems 1"),
("CSEL1"),
("IPR"),
("NSA"),
("Réseaux et applications IT 1"),
("Systèmes d'information 2"),
("Betriebswirtschaft/Economie d'entreprise"),
("Projet de semestre 5"),
("Systèmes embarqués 3"),
("TP Traitement images et Audio"),
("Recherche opérationnelle"),
("Architectures des réseaux"),
("Modelisation de processus"),
("Traitement images & audio"),
("Téléinformatique"),
("TP Tech. num1/Téléinf1"),
("TP Tech. num./Teleinfo 1"),
("TP Rés IP1/Sys d'expl1"),
("TP Num. Technik/Teleinf. 1"),
("TP Repr de l'info/Teleinf.1"),
("TP Architectures des réseaux"),
("Betriebswirtschaft"),
("Chimie analytique 1"),
("Informatique 1"),
("Allgemeine und anorganische Chemie 1"),
("Chimie organique 1"),
("Séminaires & Visites / Administration"),
("Séminaires & Visites"),
("Initiation a la conception"),
("Physique et simulation"),
("Economie d'entreprise"),
("Statique"),
("Gestion de projet"),
("Statistiques"),
("Bases de données 1"),
("Mathématiques spécifiques 1"),
("TP Bases de données"),
("Génie logiciel 1 & TP"),
("Algorithmique 2"),
("Systèmes embarqués 1"),
("Programmation concurrente 1"),
("Construction en béton 1"),
("Géotechnique, mécanique des sols 1"),
("Résistance des matériaux 1"),
("Construction et environnement 1"),
("Hydraulique générale 1"),
("Systèmes d'information du territoire"),
("Hydraulik 1"),
("Gestion de la construction 1"),
("Technol. des matériaux 1 & TP"),
("Analysis 3"),
("Calcul des structures 1"),
("Mensuration 1"),
("Bases environnementales 1"),
("Methodologie"),
("Génie logiciel"),
("Réseaux IP 1"),
("ProjektManagement"),
("Signaux et systèmes électroniques"),
("Systèmes numériques 1"),
("Systèmes d'exploitation"),
("All. 1/Photo 1/Détails constr. A"),
("Embedded Systems 1"),
("Mathématiques 1"),
("Projet E-commerce"),
("Englisch 1"),
("Comptabilité générale"),
("E-Marketing"),
("Analyse financière"),
("Phys. 1/Maths. 1/Hist. de l'art"),
("Numerische Technik 1"),
("Teleinformatik 1"),
("Programmierung & TP"),
("Représentation de l'information"),
("Digitales Entwerfen"),
("Expr. informatique 3"),
("Baustatik 1"),
("Grundlagen Umweltwissenschaften 1"),
("Architekturgesch. 3"),
("Anglais/Archi & immo./Déf. ses idées"),
("Kunstbewegungen/Français"),
("Architekturgeschichte 1"),
("TP Matériaux de l'ing./Autom. Industr."),
("Französisch 1/Techn. Deutsch 1"),
("DFS"),
("Aérodynamique"),
("Projet de semestre"),
("CAO 1"),
("Elektrotechnik 1"),
("Anglais"),
("TP GM"),
("Moteur a combustion interne 1"),
("Transmission hydrostatique 1"),
("Automatique"),
("Projet P4"),
("Analyse de structures FEM"),
("Mécanique des fluides 2"),
("Gestion de production"),
("Thermodynamique 2"),
("Transfert de chaleur et de masse"),
("Dynamique des systèmes mécaniques 3D"),
("Schwingungslehre"),
("Simulation CFD"),
("MEMSD"),
("Conception plastique 1"),
("Polymères et matériaux innovants"),
("Structures légères et composites 1"),
("Conception de machines"),
("Projet de conception P2"),
("Eléments de machines 1"),
("Résistance des matériaux 2"),
("Funktionelle Auslegung"),
("Automatismes industriels"),
("Matériaux de l'ingénieur 3"),
("Dynamik von mechanischen Systemen 1"),
("Systèmes d'entrainement"),
("Signaux & systèmes 1"),
("Projektmanagement"),
("Elektronik 1"),
("Projet Communication visuelle"),
("Electricité 2"),
("Statistik"),
("EX 21 Signaux et systèmes électroniques"),
("Numerische Mathematik"),
("Algorithmen"),
("Mathématiques numériques"),
("Electronique 1"),
("Algorithmes"),
("Traitement du signal"),
("Circuits int. et a haute fréquence"),
("Informatique technique 2"),
("Conception syst. numériques"),
("Génie logiciel 2"),
("Interface homme-machine 2"),
("Programmation C et C++"),
("Programmation avancée Java"),
("Chap. spéc. 1 : NoSQL"),
("Chap. spéc. 2 : Trait. image et vision"),
("Chap. spéc. 3 : Adv. Interfaces & Wearable"),
("Bases de données 2"),
("Programmation logique"),
("Développement mobile Cross Plate-Forme"),
("Applications mobiles 2"),
("Programmation"),
("Mathematik 1"),
("Electricité 1"),
("Matériaux"),
("Systèmes logiques"),
("Techniques des télécoms 1"),
("Réseaux électriques 1"),
("Electrom. et entr. él. 1"),
("Electronique de puis. 1"),
("Smart Energy Systems 1"),
("Machines électriques 1"),
("Automatique 2"),
("Haute tension 1"),
("Technologie Internet"),
("Projet d'architecture 3"),
("Entwurfslehre 3"),
("Expression plastique 3"),
("A dispo : ex. interdisciplinaires"),
("Projet d'architecture 5"),
("Entwurfslehre 5"),
("Expression plast. et design 5"),
("TP 52 Réseaux El1/Haute tension1"),
("TP 53 El. de puis/Electrom. et entr. él. 1"),
("TP 32 Electroméc/Elektronik1"),
("TP 51 Mach El1/Autom2"),
("TP 32 Electroméc/Electroniq1"),
("TP 11 Métro/Syst logiques"),
("Tech. num. + électronique"),
("TP Sign & sys él./Sys num1"),
("TP Représentation de l'information"),
("TP Chimie industrielle 1"),
("Business plan"),
("F-Energy"),
("F-Physics"),
("T-Product"),
("T-EmbReal"),
("ASE"),
("T-AdvTherm"),
("T-MachLe"),
("MPRI"),
("C-QRM-A"),
("MPIT"),
("F-AppStat-A"),
("F-CompAlg-A"),
("T-MobOp"),
("SeS"),
("DYN"),
("C-Ethics-A"),
("MAGHY"),
("T-NewIPArc"),
("Cours UNIFR"),
("EPR");

-- rooms
INSERT INTO `rooms`(`name`, `description`) VALUES
("A0006","Petite salle conférence"),
("A1009","Petite salle conférence"),
("AR025","Petite salle Arsenaux"),
("AR027","Petite salle Arsenaux"),
("AR029","Grande salle Arsenaux"),
("AR031","Grande salle Arsenaux"),
("AR033","Grande salle Arsenaux"),
("AR035","Grande salle Arsenaux"),
("AR113","Grande salle Arsenaux"),
("AR117","Grande salle Arsenaux"),
("AR123","Auditoire arsenaux"),
("AUDEG","Auditoire Edouard Gremaud"),
("B0004","Petite salle de classe"),
("B0008","Labo de chimie"),
("B0022","Petite salle de classe"),
("B1016","Labo de chimie"),
("B2004","Labo de chimie"),
("B2012","Labo de chimie"),
("B3003","Labo de physique"),
("B3004","Auditoire 60 places"),
("B3008","Auditoire 30 places"),
("B3016","Auditoire 80 places"),
("B3020","Auditoire 60 places"),
("B4008","Atelier Archi"),
("B4016","Atelier Archi"),
("B4022","Atelier A-1"),
("BEA01","Grande salle Beauregard"),
("BEA02","Petite salle Beauregard"),
("BEA03","Grande salle Beauregard"),
("BEA05","Grande salle Beauregard"),
("BEA06","Petite salle Beauregard"),
("BEA10","Petite salle Beauregard"),
("BEA14","Petite salle Beauregard"),
("BFAH1","BlueFactory-PICC-AH1"),
("C0004","Salle PC"),
("C0015","Petite salle de conférence"),
("C0016","Labo d'informatique"),
("C0019","Labo d'informatique"),
("C0022","Labo d'informatique"),
("C1004","Petite salle de classe"),
("C1012","Labo de télécom"),
("C1016","Labo de télécom"),
("C1022","Labo de télécom"),
("C2006","Grande salle de classe"),
("C2012","Grande salle de classe"),
("C2018","Grande salle de classe"),
("C2022","Grande salle de classe"),
("C3006","Grande salle de classe"),
("C3012","Grande salle de classe"),
("C3016","Petite salle de classe"),
("C3020","Petite salle de classe"),
("C3022","Petite salle de classe"),
("C4003","Auditoire 40 places"),
("C4008","Atelier A-1"),
("C4016","Atelier A-1"),
("C4022","Atelier A-1"),
("D0003","Labo photo-élasticité"),
("D0004","Petite salle de classe"),
("D0008","Petite salle de classe"),
("D0013","Labo de mécanique-chimie"),
("D0016","Grande salle de classe"),
("D0022","Labo de mécanique"),
("D1006","Labo de mécanique"),
("D1014","Labo de mécanique"),
("D1022","Grande salle de classe"),
("D2004","Petite salle de classe"),
("D2008","Petite salle de classe"),
("D2012","Petite salle de classe"),
("D2018","Grande salle de classe"),
("D2022","Labo d'informatique"),
("D3004","Petite salle de classe"),
("D3008","Petite salle de classe"),
("D3012","Petite salle de classe"),
("D3016","Petite salle de classe"),
("D3020","Petite salle de classe"),
("D3022","Petite salle de classe"),
("D4008","Atelier A-2"),
("D4016","Atelier A-2"),
("D4022","Atelier A-2"),
("EIKON","Salle EIKON"),
("F0003","Labo GC (hydraulique)"),
("F0006","Labo de mécanique"),
("F0016","Labo de mécanique"),
("F0019","Labo GC (environnement)"),
("F0027","Labo GC (géotechnique)"),
("F0101","Labo GC (structure)"),
("F1006","Labo de mécanique"),
("FON23","Labo de chimie"),
("FON28","Atelier Archi"),
("FON29","Atelier Archi"),
("G0010","Labo d'électrotechnique"),
("G0015","Labo d'électrotechnique"),
("G0107","Labo d'électrotechnique"),
("G1007","Labo d'électrotechnique"),
("G1017","Labo d'électrotechnique"),
("G1022","Labo d'électrotechnique"),
("G1027","Labo d'électrotechnique"),
("H0031","Labo de chimie"),
("HEG00","Innovation Lab"),
("HEG12","Auditoire HEG"),
("LAUS1","Salle Lausanne"),
("LAUS2","Salle Lausanne"),
("SIER1","Salle Sierre"),
("SION1","Salle Sion"),
("UNIFR","Salle UNI-FR"),
("UNINE","Salle UNI-Neuch"),
("YVERD","Salle Yverdon"),
("ZH007","Salle Zürich"),
("ZH013","Salle Zürich"),
("ZH069","Salle Zürich");

-- timeslots
INSERT INTO `timeslots`(`start_hour`, `start_minute`, `end_hour`, `end_minute`) VALUES
(8,15,9,00),
(9,5,9,50),
(10,15,11,00),
(11,5,11,50),
(13,0,13,45),
(13,50,14,35),
(15,0,15,45),
(15,50,16,35),
(17,0,17,45),
(17,50,18,35);

-- weekdays
INSERT INTO `weekdays`(`name_fr`,`name_en`,`name_de`) VALUES
("Lundi", "Monday","Montag"),
("Mardi","Tuesday","Dienstag"),
("Mercredi","Wednesday","Mittwoch"),
("Jeudi","Thursday","Donnerstag"),
("Vendredi","Friday","Freitag"),
("Samedi","Saturday","Samstag"),
("Dimanche","Sunday","Sonntag");
